on:
  push:
    tags:
      - "v*"

name: Create Release

jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up env
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"
      - name: Build for linux x86_64
        run: go build -tags urfave_cli_no_docs -o updir
      - name: Create Release and upload build
        run: |
          gh release create ${{ github.ref_name }} --generate-notes
          gh release upload ${{ github.ref_name }} updir
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
